# yaml-language-server: $schema=https://blue-build.org

name: my-zirconium
description: Zirconium plus my apps
base-image: ghcr.io/zirconium-dev/zirconium
image-version: latest
modules:
  - type: dnf
    install:
      packages:
        - kitty
        - python3-uinput
        - steam-devices

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - com.google.Chrome