# yaml-language-server: $schema=https://blue-build.org

name: my-zirconium
description: Zirconium plus my apps
base-image: ghcr.io/zirconium-dev/zirconium
image-version: latest

modules:
  # Use rpm-ostree to bridge the custom Copr repository infrastructure
  - type: rpm-ostree
    repos:
      - https://fedorainfracloud.org
    install:
      - kitty
      - squeekboard                  # Resolves perfectly now via the mobile copr layer


  # Deploy your custom wide desktop yaml layout to the system profile
  - type: files
    files:
      - src: usr/share/squeekboard/keyboards/terminal/us.yaml
        dest: /usr/share/squeekboard/keyboards/terminal/us.yaml

  # Automatically enable the screen keyboard system flag on boot
  - type: gschema-overrides
    include:
      - 01-squeekboard.gschema.override

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - com.google.Chrome
